stages:
  - build
  - docker
  - deploy

build_jar:
  image: openjdk:17-alpine
  stage: build
  script:
    - apk add --no-cache maven
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/app.jar
    expire_in: 1 hour 

build_image:
  image: docker
  stage: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/group11820151/k8s-data/myapp:latest .
    - docker push $CI_REGISTRY/group11820151/k8s-data/myapp:latest
    - echo "build image"  

deploy_to_k8s:
  stage: deploy
  image:  
    name: bitnami/kubectl:latest 
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context group11820151/k8s-connection:k8s-connection
    - kubectl set image deployment/myapp myapp=$CI_REGISTRY/group11820151/k8s-data/myapp:latest -n myapp
    - kubectl rollout restart deployment/myapp -n myapp
    - kubectl rollout status deployment/myapp -n myapp
    - kubectl get pods -n myapp

   