stages:
  - build
  - docker

build_jar:
  image: openjdk:17-alpine
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/app.jar
    expire_in: 1 hour

build_image:
  image: docker
  stage: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/group11820151/k8s-data/myapp:latest .
    - docker push $CI_REGISTRY/group11820151/k8s-data/myapp:latest
    - echo "build image"