server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${SECRET_DB_HOST:localhost}:${SECRET_DB_PORT:5432}/backend
    username: ${SECRET_DB_USERNAME:postgres}
    password: ${SECRET_DB_PASSWORD:syspass}
  kafka:
    bootstrap-servers: ${SECRET_KAFKA_HOST:localhost}:${SECRET_KAFKA_PORT:9092}
  data:
    redis:
      host: ${SECRET_REDIS_HOST:localhost}
      port: ${SECRET_REDIS_PORT:6379}
      password: ${SECRET_REDIS_PASSWORD:redispass}
  cache:
    type: redis
    redis:
      time-to-live: 300000
app:
  token:
    secret: ${SECRET_JWT_SECRET:'m#mySecret@2023'}
    issuer: MyAppService